### ISSUE TITLE
Separate the question endpoint function into two functions

### ISSUE THREAD

**Issue by matt989253** [heig-PRO-b04/elm-frontend#129]
**Current situation :**

1. The question endpoint takes a Maybe Int for when you wish to use the /question/idQuestion endpoint, or just the /question one
2. As these two endpoints are conceptually quite different, they should not be in the same function

**Sub-tasks that need to be performed :**

- [x] Separate the two endpoints into different functions
- [x] Apply the changes to every use of the endpoint function

**Comment by alexandrepiveteau** [comment]
Is this fixed ?

**Comment by matt989253** [comment]
It is
