### ISSUE TITLE
Change hrefs to Routes, for all clickable elements

### ISSUE THREAD

**Issue by matt989253** [heig-PRO-b04/elm-frontend#35]
Need to change / add Routes to:
- Sign in button
- Sign up button
- Main title (send back to home page)

Not sure about external links:
- Get the app
- Github page in the footer

**Comment by alexandrepiveteau** [comment]
External links are added as standard `Html.href` attributes afaik.

**Comment by alexandrepiveteau** [comment]
Can we consider this fixed ?

**Comment by matt989253** [comment]
Yes
