### ISSUE TITLE
Fix dropdown menu on mobile devices

### ISSUE THREAD

**Issue by matt989253** [heig-PRO-b04/elm-frontend#66]
**Current situation :**

1. The user logo wraps aroung the navigation bar on mobile devices
2. The dropdown menu isn't aligned properly with the user logo when this happens

**Sub-tasks that need to be performed :**

- [ ] Set the user logo on mobile devices to a fixed position
- [ ] Make sure the dropdown menu is properly aligned with the user logo

**Comment by alexandrepiveteau** [comment]
This will be partially fixed (although not perfectly) with #82.
